spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: lulugroup
    stringtopicName: stringtopic
    usertopicName: usertopic
    errortopicName: errortpoc
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB